// REQUIRES: system-linux
// RUN: clang -o %t %s -O2
// RUN: llvm-mctoll -d %t
// RUN: clang -o %t1 %t-dis.ll
// RUN: %t1 2>&1 | FileCheck %s
// CHECK: 20
// CHECK: 22
// CHECK: 42

/* Binary generated by compiling at opt-level O2 generates multiple
   push instructions. This results in exercising the stack allocation
   done while raising push instructions.
 */

#include <stdio.h>
int Func(int Val1, int Val2) {
  printf("%d\n", 2 * Val1);
  printf("%d\n", 2 * Val2);
  return 2 * (Val1 + Val2);
}
int main() {
  int RetVal = Func(10, 11);
  printf("%d\n", RetVal);
  return 0;
}
